Repository ksubi666/Joy, pull requests merged in 2024-10, with the labels that each got.

#5 [BE] initial setup
  BE/.gitignore
  BE/package-lock.json
  BE/package.json
  BE/src/index.ts
  BE/tsconfig.json
  FE/.eslintrc.json
  FE/.gitignore
  FE/README.md
  FE/next-env.d.ts
  FE/next.config.mjs
  FE/package-lock.json
  FE/package.json
  FE/postcss.config.mjs
  FE/src/app/favicon.ico
  FE/src/app/fonts/GeistMonoVF.woff
  FE/src/app/fonts/GeistVF.woff
  FE/src/app/globals.css
  FE/src/app/layout.tsx
  FE/src/app/page.tsx
  FE/tailwind.config.ts
  FE/tsconfig.json
Labels: Backend

#7 eslint rule
  BE/tsconfig.json
  FE/.eslintrc.json
Labels: Frontend, Backend

#38 [BE] user schema
  BE/src/schema/user.ts
  FE/eslint.config.mjs
  FE/package-lock.json
  FE/package.json
Labels: Backend

#39 [BE] product schema
  BE/src/schema/product.ts
Labels: Backend

#41 [BE] user Create query
  BE/package-lock.json
  BE/package.json
  BE/src/Utills/db.ts
  BE/src/controller/user.ts
  BE/src/index.ts
  BE/src/routes/User.ts
Labels: Backend

#40 [BE] wishlist schema
  BE/src/schema/wishlist.ts
Labels: Backend

#43 [BE] user get query
  BE/package-lock.json
  BE/package.json
  BE/src/controller/user.ts
  BE/src/index.ts
  BE/src/routes/User.ts
  BE/src/schema/wishlist.ts
Labels: Backend

#44 [BE] category schema
  BE/src/schema/category.ts
Labels: Backend

#48 [BE] review schema
  BE/src/schema/review.ts
Labels: Backend

#46 [BE] order schema
  BE/src/schema/order.ts
Labels: Backend

#45 [BE] cart schema
  BE/src/schema/cart.ts
Labels: Backend

#50 [BE] user update and delete
  BE/package-lock.json
  BE/package.json
  BE/src/controller/user.ts
Labels: Backend

#52 [BE] category CRUD
  BE/src/controller/category.ts
  BE/src/schema/category.ts
Labels: Backend

#53 28 be products crud
  BE/src/controller/product.ts
Labels: Backend

#54 [BE] cart CRUD
  BE/src/controller/cart.ts
Labels: Backend

#60 [FE] Cloudflare setup
  BE/src/controller/user.ts
  BE/src/index.ts
  BE/src/routes/User.ts
  FE/package-lock.json
  FE/package.json
  FE/src/app/api/upload/route.ts
  package.json
Labels: Frontend

#61 [FE] shadcn setup
  FE/components.json
  FE/package-lock.json
  FE/package.json
  FE/src/app/globals.css
  FE/src/components/ui/button.tsx
  FE/tailwind.config.ts
Labels: Frontend

#62 [FE] navbar only ui
  FE/src/app/icons/SearchIcon.tsx
  FE/src/app/layout.tsx
  FE/src/app/page.tsx
  FE/src/components/Navbar.tsx
  FE/src/lib/utils.ts
Labels: Frontend

#64 [FE] next image config
  FE/next.config.mjs
  FE/src/app/page.tsx
Labels: Frontend

#66 [FE] card ...
  FE/src/app/page.tsx
  FE/src/components/Card.tsx
  FE/tailwind.config.ts
Labels: Frontend

#67 Footer only ui
  FE/src/app/layout.tsx
  FE/src/components/Footer.tsx
  FE/src/components/Svgs.tsx
Labels: Frontend

#69 [FE] Subcategory only ui
  FE/src/app/page.tsx
  FE/src/components/Subcategory.tsx
Labels: Frontend

#68 11 fe main section
  FE/src/app/index.tsx
  FE/src/app/page.tsx
  FE/src/components/MainPage.tsx
  FE/src/components/Navbar.tsx
Labels: Frontend

#71 [FE] refactor mainsection and subcategory
  FE/src/app/layout.tsx
  FE/src/app/page.tsx
  FE/src/components/MainPage.tsx
  FE/src/components/Navbar.tsx
  FE/src/components/Subcategory.tsx
Labels: Frontend

#72 [FE] card component only ui
  FE/src/app/page.tsx
  FE/src/components/Card.tsx
Labels: Frontend

#73 [FE] admin dashboard
  BE/package-lock.json
  BE/package.json
  BE/src/controller/product.ts
  BE/src/controller/subCategory.ts
  BE/src/index.ts
  BE/src/routes/subCategory.ts
  BE/src/schema/product.ts
  BE/src/schema/subCategory.ts
  FE/package-lock.json
  FE/package.json
  FE/src/app/admin/page.tsx
  FE/src/app/globals.css
  FE/src/app/layout.tsx
  FE/src/app/not-found.tsx
  FE/src/components/AdminAddCategory.jsx
  FE/src/components/AdminAddSubCategory.tsx
  FE/src/components/AdminCategory.tsx
  FE/src/components/AdminSideBar.tsx
  FE/src/components/Card.tsx
  FE/src/components/Footer.tsx
  FE/src/components/ui/alert-dialog.tsx
  FE/src/components/ui/input.tsx
  FE/src/components/ui/select.tsx
Labels: Frontend

#75 [FE] bug fix category dialog
  FE/src/components/AdminAddCategory.jsx
  FE/src/components/AdminAddSubCategory.tsx
Labels: Frontend

#77 [FE] admin dashboard refactor
  FE/src/app/admin/page.tsx
  FE/src/app/api/upload/route.ts
  FE/src/app/page.tsx
  FE/src/components/AdminAddCategory.tsx
  FE/src/components/AdminCategory.tsx
  FE/src/components/Card.tsx
  FE/src/components/Footer.tsx
  FE/src/components/ProductDetail.tsx
  FE/src/components/ProductEditDialog.tsx
  FE/src/components/ui/input.tsx
Labels: Frontend

#79 [BE] refactor imports
  BE/package-lock.json
  BE/package.json
  BE/src/controller/cart.ts
  BE/src/controller/category.ts
  BE/src/controller/product.ts
  BE/src/controller/subCategory.ts
  BE/src/controller/user.ts
  BE/src/controller/wishlist.ts
  BE/src/routes/subCategory.ts
Labels: Backend

#82 [FE] admin dashboard refactor
  BE/src/controller/subCategory.ts
  BE/src/index.ts
  BE/src/routes/subCategory.ts
  BE/src/schema/subCategory.ts
  FE/src/app/admin/page.tsx
  FE/src/components/AdminAddCategory.tsx
  FE/src/components/AdminProducts.tsx
  FE/src/components/AdminSideBar.tsx
  FE/src/components/AdminSideBard.tsx
  FE/src/components/Card.tsx
Labels: Frontend

#80 [FE] login page
  FE/package-lock.json
  FE/package.json
  FE/src/app/login/page.tsx
  FE/src/app/page.tsx
  FE/src/components/Card2.tsx
  FE/src/components/Trending.tsx
Labels: Frontend

#83 [FE] leaflet setup
  BE/src/controller/product.ts
  BE/src/schema/product.ts
  FE/package-lock.json
  FE/package.json
  FE/src/app/globals.css
  FE/src/app/page.tsx
  FE/src/components/Map.tsx
  FE/src/components/ProductDetail.tsx
Labels: Frontend

#84 [FE] card detail page
  FE/package-lock.json
  FE/package.json
  FE/src/components/DetailPageCarousel.tsx
  FE/src/components/ProductDetail.tsx
  FE/src/components/ui/card.tsx
  FE/src/components/ui/carousel.tsx
Labels: Frontend

#86 [FE] refactor admin dashboard
  FE/src/app/admin/page.tsx
  FE/src/app/index.tsx
  FE/src/assets/JOY.png
  FE/src/components/AdminAddCategory.tsx
  FE/src/components/AdminAddProduct.tsx
  FE/src/components/AdminProducts.tsx
  FE/src/components/AdminSideBard.tsx
  FE/src/components/Navbar.tsx
  FE/src/components/ProductDetail.tsx
Labels: Frontend

#88 [FE] signup page only ui
  FE/src/app/globals.css
  FE/src/app/page.tsx
  FE/src/app/signup/page.tsx
Labels: Frontend

#90 [FE] admin dashboard insight
  FE/package-lock.json
  FE/package.json
  FE/src/app/admin/page.tsx
  FE/src/components/AdminInsight.tsx
  FE/src/components/AdminProducts.tsx
  FE/src/components/InsightCard.tsx
  FE/src/components/InsigthChart.tsx
  FE/src/components/ui/chart.tsx
Labels: Frontend

#92 [FE] category create & category list & axios utill func+&refactor [BE…
  BE/src/controller/category.ts
  BE/src/index.ts
  BE/src/routes/Category.ts
  FE/src/app/admin/page.tsx
  FE/src/components/AdminAddCategory.tsx
  FE/src/components/AdminProducts.tsx
  FE/src/components/AdminSideBard.tsx
  FE/src/components/ProductEditDialog.tsx
  FE/src/lib/axios.ts
Labels: Frontend, Backend

#93 [FE] product list & refactor
  FE/src/app/page.tsx
  FE/src/components/AdminProducts.tsx
  FE/src/components/Card.tsx
  FE/src/components/MainPage.tsx
  FE/src/components/Navbar.tsx
  FE/src/components/ProductEditDialog.tsx
  FE/src/components/ProductsList.tsx
  FE/src/components/Subcategory.tsx
Labels: Frontend

#94 [BE] login query
  BE/src/controller/auth.ts
  FE/src/app/signup/page.tsx
Labels: Backend

#96 [FE] Insight order list UI
  FE/src/components/AdminInsight.tsx
  FE/src/components/InsightOrderTitles.tsx
  FE/src/components/InsightOrders.tsx
  FE/src/components/MainPage.tsx
Labels: Frontend

#98 [FE] refactor Insight order
  FE/src/components/AdminInsight.tsx
Labels: Frontend

#100 [FE] bug fix
  FE/src/components/AdminInsight.tsx
Labels: bug

#105 [BE] deploy setup
  BE/.gitignore
  BE/package.json
  BE/src/index.ts
  BE/vercel.json
Labels: Backend

#108 [BE] refactor vercel.json docker setup
  BE/package-lock.json
  BE/package.json
  BE/src/index.ts
  BE/vercel.json
Labels: Backend

#106 [FE] Cart ui
  FE/src/app/cart/page.tsx
  FE/src/app/page.tsx
Labels: Frontend

#103 [FE] Wishlist ui
  FE/src/app/page.tsx
  FE/src/app/wishlist/page.tsx
Labels: Frontend

#110 [FE] refactor cart & wishlist
  FE/src/app/cart/page.tsx
  FE/src/app/page.tsx
  FE/src/app/wishlist/page.tsx
  FE/src/components/Cart.tsx
  FE/src/components/Navbar.tsx
Labels: Frontend
